language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
  - pip install -e .[testing]
script:
  - pytest --cov=pytest_httpx --cov-fail-under=100 --runpytest=subprocess
  - pip install idna==2.10
deploy:
  provider: pypi
  username: __token__
  edge: true
  distributions: "sdist bdist_wheel"
  skip_existing: true